Repository coverage-robot/core, pull requests merged in 2023-10, with the labels that each got.

#524 Ignore webhooks for check runs created by us
  .github/workflows/api.yml
  services/api/.env
  services/api/src/Enum/EnvironmentVariable.php
  services/api/src/Model/Webhook/Github/GithubCheckRunWebhook.php
  services/api/src/Model/Webhook/PipelineStateChangeWebhookInterface.php
  services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
  services/api/tests/Handler/WebhookHandlerTest.php
  services/api/tests/Service/Webhook/JobStateChangeWebhookProcessorTest.php
Labels: bug, skip-changelog

#525 Cast the app id to a string for comparisons
  services/api/src/Model/Webhook/Github/GithubCheckRunWebhook.php
Labels: bug, skip-changelog

#526 Fix final check run finish state change
  services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
  services/publish/src/Service/Formatter/CheckRunFormatterService.php
  services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
  services/publish/tests/Service/Formatter/CheckRunFormatterServiceTest.php
Labels: bug, skip-changelog

#527 Handle null case for uploads query
  services/analyse/src/Query/TotalUploadsQuery.php
  services/analyse/tests/Query/TotalUploadsQueryTest.php
Labels: bug, skip-changelog

#528 Remove check run update during uploads
  services/analyse/src/Service/Event/IngestSuccessEventProcessor.php
  services/analyse/tests/Service/Event/IngestSuccessEventProcessorTest.php
Labels: chore, skip-changelog

#529 Keep check run in sync during uploads
  packages/models/src/Model/PublishableMessage/PublishableCheckRunMessage.php
  services/analyse/src/Service/Event/IngestSuccessEventProcessor.php
  services/analyse/tests/Service/Event/IngestSuccessEventProcessorTest.php
  services/publish/src/Service/Publisher/Github/AbstractGithubCheckPublisherService.php
  services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
Labels: feature, skip-changelog

#537 Add correct interface to publisher
  services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
Labels: feature, skip-changelog

#543 Only consider webhooks finished on last record
  services/api/src/Handler/WebhookHandler.php
  services/api/src/Model/Webhook/Github/GithubCheckRunWebhook.php
  services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
  services/api/src/Service/Webhook/WebhookProcessor.php
  services/api/src/Service/Webhook/WebhookProcessorInterface.php
  services/api/tests/Service/Webhook/JobStateChangeWebhookProcessorTest.php
  services/api/tests/Service/Webhook/WebhookProcessorTest.php
Labels: bug, bump-patch

#545 Switch to using a bigquery load job to import data rather than streaming
  infrastructure/warehouse/main.tf
  services/ingest/composer.json
  services/ingest/composer.lock
  services/ingest/src/Client/GoogleCloudStorageClient.php
  services/ingest/src/Service/Persist/BigQueryPersistService.php
  services/ingest/src/Service/Persist/EventBridgePersistService.php
  services/ingest/src/Service/Persist/GcsPersistService.php
  services/ingest/src/Service/Persist/S3PersistService.php
  services/ingest/tests/Service/CoverageFilePersistServiceTest.php
  services/ingest/tests/Service/Persist/BigQueryPersistServiceTest.php
  services/ingest/tests/Service/Persist/EventBridgePersistServiceTest.php
  services/ingest/tests/Service/Persist/GcsPersistServiceTest.php
Labels: feature, bump-patch

#546 Switch bucket region and add lifecycle
  infrastructure/warehouse/main.tf
Labels: feature, bump-patch

#547 Remove close buffer
  services/ingest/src/Service/Persist/GcsPersistService.php
  services/ingest/src/Service/Persist/S3PersistService.php
Labels: feature, bump-patch

#544 Refactor the pipeline events into job state change events
  packages/clients/src/Client/Github/GithubAppInstallationClient.php
  packages/models/src/Enum/EventBus/CoverageEvent.php
  packages/models/src/Enum/EventType.php
  packages/models/src/Enum/JobState.php
  packages/models/src/Model/Event/EventInterface.php
  packages/models/src/Model/Event/JobStateChange.php
  packages/models/src/Model/Event/PipelineComplete.php
  packages/models/src/Model/Event/PipelineStarted.php
  services/analyse/infrastructure/analyse/main.tf
  services/analyse/src/Handler/EventHandler.php
  services/analyse/src/Service/Event/EventProcessorInterface.php
  services/analyse/src/Service/Event/IngestSuccessEventProcessor.php
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
  services/analyse/src/Service/Event/PipelineCompleteEventProcessor.php
  services/analyse/src/Service/Event/PipelineStartedEventProcessor.php
  services/analyse/tests/Handler/EventHandlerTest.php
  services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
  services/analyse/tests/Service/Event/PipelineCompleteEventProcessorTest.php
  services/analyse/tests/Service/Event/PipelineStartedEventProcessorTest.php
  services/api/src/Entity/Job.php
  services/api/src/Enum/WebhookProcessorEvent.php
  services/api/src/Handler/WebhookHandler.php
  services/api/src/Model/Webhook/Github/GithubCheckRunWebhook.php
  services/api/src/Model/Webhook/PipelineStateChangeWebhookInterface.php
  services/api/src/Repository/JobRepository.php
  services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
  services/api/src/Service/Webhook/WebhookProcessor.php
  services/api/src/Service/Webhook/WebhookProcessorInterface.php
  services/api/tests/Client/EventBridgeEventClientTest.php
  services/api/tests/Handler/WebhookHandlerTest.php
  services/api/tests/Service/Webhook/JobStateChangeWebhookProcessorTest.php
  services/api/tests/Service/Webhook/WebhookProcessorTest.php
Labels: chore, bump-patch

#548 Update state change model
  packages/models/src/Model/Event/JobStateChange.php
  services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
Labels: bug, skip-changelog

#549 Use commit for checking check run state
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
Labels: bug, skip-changelog

#550 Authenticate as repo owner before querying check runs
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
Labels: bug, skip-changelog

#551 Fix the status validation
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
Labels: bug, skip-changelog

#552 Use correct path
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
Labels: bug, skip-changelog

#553 Use correct path
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
Labels: bug, skip-changelog

#554 Exclude self published check runs
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
  services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
Labels: bug, skip-changelog

#555 Deduplicate check run annotations when publishing
  services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
  services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
Labels: feature, bump-patch

#556 Use correct path for annotation count information
  services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
  services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
Labels: bug, skip-changelog

#557 Only persist coverage when it includes at least one file
  services/ingest/src/Handler/EventHandler.php
  services/ingest/tests/Handler/EventHandlerTest.php
Labels: chore, bump-patch

#558 Handle multiple pages of check annotations
  packages/clients/src/Client/Github/GithubAppInstallationClient.php
  services/publish/src/Service/Publisher/Github/GithubCheckRunPublisherService.php
Labels: bug, bump-patch

#569 Set clustering on warehouse line coverage dataset
  infrastructure/warehouse/main.tf
Labels: chore, skip-changelog

#570 [Part 1] Add dedicated table for uploads
  infrastructure/warehouse/main.tf
  infrastructure/warehouse/outputs.tf
Labels: feature, bump-minor

#572 Allow upload table as output for remote state
  infrastructure/outputs.tf
Labels: skip-changelog

#571 [Part 2] Stream uploads into new table
  services/ingest/.env
  services/ingest/.env.dev
  services/ingest/infrastructure/ingest/main.tf
  services/ingest/src/Enum/EnvironmentVariable.php
  services/ingest/src/Service/BigQueryMetadataBuilderService.php
  services/ingest/src/Service/Persist/GcsPersistService.php
  services/ingest/tests/Service/BigQueryMetadataBuilderServiceTest.php
  services/ingest/tests/Service/Persist/GcsPersistServiceTest.php
Labels: feature, bump-minor

#573 [Part 3] Move upload queries into more efficient upload table
  infrastructure/warehouse/main.tf
  services/analyse/.env
  services/analyse/infrastructure/analyse/main.tf
  services/analyse/src/Client/BigQueryClient.php
  services/analyse/src/Enum/EnvironmentVariable.php
  services/analyse/src/Model/PublishableCoverageData.php
  services/analyse/src/Model/PublishableCoverageDataInterface.php
  services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
  services/analyse/src/Query/CommitSuccessfulTagsQuery.php
  services/analyse/src/Query/QueryInterface.php
  services/analyse/src/Query/Result/TotalUploadsQueryResult.php
  services/analyse/src/Query/TotalUploadsQuery.php
  services/analyse/src/Query/Trait/UploadTableAwareTrait.php
  services/analyse/src/Service/Event/IngestSuccessEventProcessor.php
  services/analyse/src/Service/QueryService.php
  services/analyse/tests/Mock/Factory/MockQueryFactory.php
  services/analyse/tests/Model/CachingPublishableCoverageDataTest.php
  services/analyse/tests/Query/CommitSuccessfulTagsQueryTest.php
  services/analyse/tests/Query/FileCoverageQueryTest.php
  services/analyse/tests/Query/LineCoverageQueryTest.php
  services/analyse/tests/Query/TotalCoverageQueryTest.php
  services/analyse/tests/Query/TotalTagCoverageQueryTest.php
  services/analyse/tests/Query/TotalUploadsQueryTest.php
  services/analyse/tests/Service/QueryServiceTest.php
Labels: feature, bump-patch

#574 Fix incorrect grouping on upload query
  services/analyse/src/Query/TotalUploadsQuery.php
  services/analyse/tests/Query/TotalUploadsQueryTest.php
Labels: feature, skip-changelog

#575 [Part 4] Move coverage queries to use uploads table
  infrastructure/warehouse/main.tf
  services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
  services/analyse/src/Query/FileCoverageQuery.php
  services/analyse/src/Query/LineCoverageQuery.php
  services/analyse/src/Query/TotalCoverageQuery.php
  services/analyse/src/Query/TotalTagCoverageQuery.php
  services/analyse/src/Query/Trait/CarryforwardAwareTrait.php
  services/analyse/src/Query/Trait/DiffAwareTrait.php
  services/analyse/src/Query/Trait/ScopeAwareTrait.php
  services/analyse/tests/Client/BigQueryClientTest.php
  services/analyse/tests/Query/FileCoverageQueryTest.php
  services/analyse/tests/Query/LineCoverageQueryTest.php
  services/analyse/tests/Query/TotalCoverageQueryTest.php
  services/analyse/tests/Query/TotalTagCoverageQueryTest.php
  services/ingest/tests/Client/BigQueryClientTest.php
Labels: feature, bump-minor

#577 Fix bug in SQL composition
  services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
Labels: skip-changelog

#576 Fix uploads for commit sql grouping
  services/analyse/src/Query/TotalUploadsQuery.php
  services/analyse/tests/Query/TotalUploadsQueryTest.php
Labels: feature, skip-changelog

#579 Only post PR comments when jobs have finished
  services/analyse/infrastructure/analyse/main.tf
  services/analyse/src/Service/Event/IngestSuccessEventProcessor.php
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
  services/analyse/tests/Handler/EventHandlerTest.php
  services/analyse/tests/Service/Event/IngestSuccessEventProcessorTest.php
Labels: feature, bump-patch

#581 Allow publisher to accept any event interface
  services/publish/src/Service/Formatter/PullRequestCommentFormatterService.php
  services/publish/src/Service/Publisher/Github/GithubPullRequestCommentPublisherService.php
  services/publish/tests/Fixture/PullRequestComment/file-and-tag-pending-uploads.txt
  services/publish/tests/Fixture/PullRequestComment/file-and-tag.txt
  services/publish/tests/Service/Publisher/Github/GithubCheckRunPublisherServiceTest.php
Labels: bug, skip-changelog

#580 Turn off retires on analyse failures
  services/analyse/infrastructure/analyse/main.tf
Labels: chore, skip-changelog

#582 fix simple typo
  README.md
Labels: chore, bump-patch

#583 Cluster line coverage on file name
  infrastructure/warehouse/main.tf
Labels: chore, bump-patch

#584 Handle no uploads on commit
  services/analyse/src/Query/TotalUploadsQuery.php
  services/analyse/tests/Query/TotalUploadsQueryTest.php
Labels: bug, bump-patch

#596 Reduce overlapping PR posts from new jobs being added
  infrastructure/queue/main.tf
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
Labels: chore, bump-patch

#598 Fix ignoring own check runs
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
Labels: chore, skip-changelog

#599 Additional logging
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
Labels: chore, skip-changelog

#600 Use commit sha when getting check runs
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
Labels: chore, skip-changelog

#601 Switch to using completed time as indicator of last job
  packages/models/src/Model/Event/JobStateChange.php
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
  services/analyse/tests/Handler/EventHandlerTest.php
  services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
  services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
  services/api/tests/Client/EventBridgeEventClientTest.php
Labels: chore, skip-changelog

#602 Ignore data type for external id
  packages/models/src/Model/Event/JobStateChange.php
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
Labels: skip-changelog

#603 Filter out job state changes where the state didnt change
  services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
Labels: bug, bump-patch

#610 Refactor the API event processor
  packages/models/src/Enum/EventBus/CoverageEvent.php
  packages/models/src/Model/Event/CoverageFinalised.php
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
  services/analyse/tests/Service/EventBridgeEventServiceTest.php
  services/api/src/Handler/EventHandler.php
  services/api/src/Service/Event/EventProcessor.php
  services/api/src/Service/Event/EventProcessorInterface.php
  services/api/src/Service/Event/NewCoverageFinalisedEventProcessor.php
  services/api/tests/Command/InvokeEventCommandTest.php
  services/api/tests/Handler/EventHandlerTest.php
  services/api/tests/Service/Event/EventProcessorTest.php
  services/api/tests/Service/Event/NewCoverageFinalisedEventProcessorTest.php
Labels: feature, bump-patch

#612 Denormalize from event body
  packages/models/src/Enum/EventBus/CoverageEvent.php
  packages/models/src/Enum/EventType.php
  packages/models/src/Model/Event/EventInterface.php
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
  services/analyse/tests/Service/EventBridgeEventServiceTest.php
  services/api/infrastructure/event_listener/main.tf
  services/api/src/Service/Event/CoverageFinalisedEventProcessor.php
  services/api/tests/Command/InvokeEventCommandTest.php
  services/api/tests/Handler/EventHandlerTest.php
  services/api/tests/Service/Event/CoverageFinalisedEventProcessorTest.php
  services/api/tests/Service/Event/EventProcessorTest.php
Labels: feature, skip-changelog

#613 Switch to long polling queues
  infrastructure/queue/main.tf
Labels: chore, bump-patch

#614 Add query cache dynamodb table
  services/analyse/.env
  services/analyse/.env.dev
  services/analyse/infrastructure/analyse/main.tf
  services/analyse/infrastructure/analyse/variables.tf
  services/analyse/infrastructure/main.tf
  services/analyse/infrastructure/query_cache/main.tf
  services/analyse/infrastructure/query_cache/outputs.tf
  services/analyse/infrastructure/query_cache/variables.tf
Labels: feature, bump-patch

#615 [Part 2] Use query cache as data store
  services/analyse/composer.json
  services/analyse/composer.lock
  services/analyse/src/Client/DynamoDbClient.php
  services/analyse/src/Enum/EnvironmentVariable.php
  services/analyse/src/Enum/QueryParameter.php
  services/analyse/src/Model/PublishableCoverageData.php
  services/analyse/src/Model/QueryParameterBag.php
  services/analyse/src/Query/CommitSuccessfulTagsQuery.php
  services/analyse/src/Query/Result/QueryResultInterface.php
  services/analyse/src/Query/TotalUploadsQuery.php
  services/analyse/src/Service/CachingQueryService.php
  services/analyse/src/Service/Carryforward/CarryforwardTagService.php
  services/analyse/src/Service/CoverageAnalyserService.php
  services/analyse/src/Service/QueryService.php
  services/analyse/src/Service/QueryServiceInterface.php
  services/analyse/tests/Client/DynamoDbClientTest.php
  services/analyse/tests/Service/CachingQueryServiceTest.php
  services/analyse/tests/Service/QueryServiceTest.php
Labels: feature, bump-minor

#616 Use query cache
  services/analyse/src/Query/Result/CommitCollectionQueryResult.php
  services/analyse/src/Query/Result/CommitQueryResult.php
  services/analyse/src/Query/Result/CoverageQueryResult.php
  services/analyse/src/Query/Result/FileCoverageCollectionQueryResult.php
  services/analyse/src/Query/Result/FileCoverageQueryResult.php
  services/analyse/src/Query/Result/LineCoverageCollectionQueryResult.php
  services/analyse/src/Query/Result/TagCoverageCollectionQueryResult.php
  services/analyse/src/Query/Result/TagCoverageQueryResult.php
  services/analyse/src/Query/Result/TotalUploadsQueryResult.php
  services/analyse/src/Service/CachingQueryService.php
Labels: feature, skip-changelog

#617 Add conditional caching support for queries which need to be short lived
  services/analyse/src/Query/AbstractUnnestedLineMetadataQuery.php
  services/analyse/src/Query/CommitSuccessfulTagsQuery.php
  services/analyse/src/Query/QueryInterface.php
  services/analyse/src/Query/TotalUploadsQuery.php
  services/analyse/src/Service/CachingQueryService.php
  services/analyse/src/Service/QueryService.php
  services/analyse/tests/Service/CachingQueryServiceTest.php
Labels: feature, bump-patch

#618 Ensure query hashes are predictable regardless of parameter order
  services/analyse/src/Enum/QueryParameter.php
  services/analyse/src/Service/CachingQueryService.php
  services/analyse/src/Service/QueryBuilderService.php
  services/analyse/tests/Query/AbstractQueryTestCase.php
  services/analyse/tests/Service/CachingQueryServiceTest.php
  services/analyse/tests/Service/QueryBuilderServiceTest.php
Labels: bug, bump-patch

#619 Add additional tests for predictable hashes
  services/analyse/tests/Service/QueryBuilderServiceTest.php
Labels: chore, skip-changelog

#636 Update documentation
  resources/architecture.jpg
Labels: chore, skip-changelog

#638 Delete older outputted coverage models to save space
  infrastructure/bucket/main.tf
Labels: chore, bump-patch

#639 Fix ttl attribute mismatch on query cache
  services/analyse/src/Client/DynamoDbClient.php
  services/analyse/tests/Client/DynamoDbClientTest.php
Labels: bug, skip-changelog

#640 Enable delete protection for query cache
  services/analyse/infrastructure/query_cache/main.tf
Labels: chore

#641 Remove unused variable
  services/analyse/infrastructure/query_cache/main.tf
  services/analyse/infrastructure/query_cache/variables.tf
Labels: feature, skip-changelog

#642 Preserve memory by using enums for discrimination of query results as opposed to the FQCN
  services/analyse/src/Enum/QueryResult.php
  services/analyse/src/Query/Result/QueryResultInterface.php
Labels: chore, bump-patch

#643 Replace manual deserialization of query results with automatic serialization
  services/analyse/src/Query/CommitSuccessfulTagsQuery.php
  services/analyse/src/Query/FileCoverageQuery.php
  services/analyse/src/Query/LineCoverageQuery.php
  services/analyse/src/Query/Result/CommitCollectionQueryResult.php
  services/analyse/src/Query/Result/CommitQueryResult.php
  services/analyse/src/Query/Result/CoverageQueryResult.php
  services/analyse/src/Query/Result/FileCoverageCollectionQueryResult.php
  services/analyse/src/Query/Result/FileCoverageQueryResult.php
  services/analyse/src/Query/Result/LineCoverageCollectionQueryResult.php
  services/analyse/src/Query/Result/LineCoverageQueryResult.php
  services/analyse/src/Query/Result/TagCoverageCollectionQueryResult.php
  services/analyse/src/Query/Result/TagCoverageQueryResult.php
  services/analyse/src/Query/Result/TotalUploadsQueryResult.php
  services/analyse/src/Query/TotalCoverageQuery.php
  services/analyse/src/Query/TotalTagCoverageQuery.php
  services/analyse/src/Query/TotalUploadsQuery.php
  services/analyse/src/Query/Trait/UploadTableAwareTrait.php
  services/analyse/tests/Client/DynamoDbClientTest.php
  services/analyse/tests/Mock/Factory/MockQueryFactory.php
  services/analyse/tests/Model/CachingPublishableCoverageDataTest.php
  services/analyse/tests/Query/AbstractQueryTestCase.php
  services/analyse/tests/Query/CommitSuccessfulTagsQueryTest.php
  services/analyse/tests/Query/FileCoverageQueryTest.php
  services/analyse/tests/Query/LineCoverageQueryTest.php
  services/analyse/tests/Query/TotalCoverageQueryTest.php
  services/analyse/tests/Query/TotalTagCoverageQueryTest.php
  services/analyse/tests/Query/TotalUploadsQueryTest.php
  services/analyse/tests/Service/CachingQueryServiceTest.php
  services/analyse/tests/Service/Carryforward/CarryforwardTagServiceTest.php
  services/analyse/tests/Service/QueryBuilderServiceTest.php
  services/analyse/tests/Service/QueryServiceTest.php
Labels: feature, bump-patch

#644 Tidy up discriminators and fix datetime conversion
  services/analyse/src/Query/Result/FileCoverageQueryResult.php
  services/analyse/src/Query/Result/TagCoverageQueryResult.php
  services/analyse/src/Query/TotalUploadsQuery.php
  services/analyse/tests/Query/TotalUploadsQueryTest.php
Labels: feature, skip-changelog

#645 Resolve queries using item iterators
  services/analyse/src/Query/CommitSuccessfulTagsQuery.php
  services/analyse/src/Query/FileCoverageQuery.php
  services/analyse/src/Query/LineCoverageQuery.php
  services/analyse/src/Query/TotalTagCoverageQuery.php
Labels: skip-changelog

#646 Ensure alias is correct on tag query
  services/analyse/src/Query/TotalTagCoverageQuery.php
  services/analyse/tests/Query/TotalTagCoverageQueryTest.php
Labels: feature, skip-changelog

#647 Rename alias for group by
  services/analyse/src/Query/TotalTagCoverageQuery.php
  services/analyse/tests/Query/TotalTagCoverageQueryTest.php
Labels: skip-changelog

#648 Fix deserialization for individual coverage objects which inherit a base class in the discriminator map
  services/analyse/src/Query/Result/FileCoverageQueryResult.php
  services/analyse/src/Query/Result/QueryResultInterface.php
  services/analyse/src/Query/Result/TagCoverageQueryResult.php
Labels: bug, bump-patch

#649 Use serializer for job state change publishable messages
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
  services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
Labels: feature, bump-patch

#650 Increase carryforward history to 200 previous commits
  services/analyse/src/Service/History/Github/GithubCommitHistoryService.php
  services/analyse/tests/Service/History/Github/GithubCommitHistoryServiceTest.php
Labels: feature, bump-patch

#651 Add additional logging for history fetching
  services/analyse/src/Service/History/Github/GithubCommitHistoryService.php
  services/analyse/tests/Service/History/Github/GithubCommitHistoryServiceTest.php
Labels: skip-changelog

#652 Fix linting
  services/analyse/src/Service/History/Github/GithubCommitHistoryService.php
Labels: skip-changelog

#656 Fix tag name comparison for existing tags which don't need carrying forward
  services/analyse/src/Service/Carryforward/CarryforwardTagService.php
  services/analyse/tests/Service/Carryforward/CarryforwardTagServiceTest.php
Labels: bug, bump-patch

#685 No longer include carried forward coverage in diff-specific coverage calculations
  services/analyse/src/Model/PublishableCoverageData.php
Labels: bug, bump-patch

#686 Include job suite state in job handling and add additional tests
  packages/models/src/Model/Event/JobStateChange.php
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
  services/analyse/tests/Handler/EventHandlerTest.php
  services/analyse/tests/Service/Carryforward/CarryforwardTagServiceTest.php
  services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
  services/api/src/Service/Webhook/JobStateChangeWebhookProcessor.php
  services/api/tests/Client/EventBridgeEventClientTest.php
Labels: bug, bump-patch

#687 Remove delay on webhook handling to see if that improves premature analysis
  infrastructure/queue/main.tf
  services/analyse/src/Service/Event/JobStateChangeEventProcessor.php
  services/analyse/tests/Service/Event/JobStateChangeEventProcessorTest.php
Labels: bug, bump-patch
